name: blueberry
favicon: null
layout_spectrum: 0.1522586087230593
typography_spectrum: 0.3663601349107921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.32433748128823936
  lightness: 0.5031379621941596
  saturation: 0.7493202155455947
  rhythmicContrast: 0.34320570691488683
purpose: []
