name: blueberry
favicon: null
layout_spectrum: 0.0668
typography_spectrum: 0.3663601349107921
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf6'
    - '#e9d9ca'
    - '#5e484b'
    - '#cba076'
    - '#99755d'
  brandStrength: 0.32433748128823936
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
