name: blueberry
favicon: null
layout_spectrum: 0.35573
typography_spectrum: 0.3663601349107921
title: under the coconut tree
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#051717'
    - '#f7eeef'
    - '#b4acd3'
    - '#737fb1'
    - '#3c4360'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
